#!/bin/bash

TEMPDIR=$(mktemp -d --tmpdir calibrate_compass.XXXX)
BAG_FILE=${TEMPDIR}/imu_record.bag
BAG_FILE_TEMP=${TEMPDIR}/imu_record-tmp.bag
CAL_FILE=${TEMPDIR}/imu_compass.yaml
CAL_FINAL_PATH=${ROS_ETC_DIR%/*}/heron_base
DURATION=60

ROSTOPIC_OUTPUT=$(rostopic list)
if [[ "$?" != "0" ]]; then
  echo "ROS appears not to be running. Please start ROS service:"
  echo "sudo service ros start"
  exit 1
fi

# Insert check for Heron active?

rospack find rosbag > /dev/null
if [[ "$?" != "0" ]]; then
  echo "Unable to find rosbag record. Is the ROS environment set up correctly?"
  exit 1
fi

rospack find heron_msgs
if [[ "$?" != "0" ]]; then
  echo "Unable to find heron_msgs. Are the heron messages built and in the ROS_PACKAGE_PATH?"
  exit 1
fi

rosbag record /tf /imu/rpy /imu/data /imu/mag_raw -O $BAG_FILE --duration $DURATION &
ROSBAG_PID=$!
echo "Started rosbag record, duration $DURATION seconds, pid [${ROSBAG_PID}]"

rostopic pub /cmd_drive heron_msgs/Drive '{ left: 0.5, right: -0.8 }' -r 15 & > /dev/null
ROSTOPIC_PID=$!
echo "Started motion commands, pid [${ROSTOPIC_PID}]"

sleep 2

echo "Test underway."

for i in $(seq 0 ${DURATION}); do
  echo -en "\rTime remaining: $((${DURATION}-i))  ";
  sleep 1
done
echo

echo "Shutting down motion command publisher."
kill $ROSTOPIC_PID

sleep 2

echo "Waiting for rosbag to shut down."

sleep 2

mv $BAG_FILE $BAG_FILE_TEMP
rosrun rosbag topic_renamer.py /imu/mag_raw $BAG_FILE_TEMP /imu/mag $BAG_FILE

echo "Computing magnetic calibration."
rosrun imu_compass compute_calibration $BAG_FILE $CAL_FILE &> /tmp/compute_output.log
if [[ "$?" != "0" ]]; then
  echo "Unable to compute calibration from recorded bag."
  echo "Output in /tmp/compute_output.log"
  exit 1
fi

if [[ -r $CAL_FILE ]]; then
  echo "Calibration generated in $CAL_FILE."
  read -r -p "Use this calibration? [Y/n] " response
  response=${response,,}    # tolower
  if [[ $response =~ ^(no|n)$ ]]; then
    echo "Skipping."
  else
    bash /home/administrator/catkin_ws/src/heron_robot/heron_bringup/scripts/calibration_write.sh < $CAL_FILE > /home/administrator/catkin_ws/src/heron_robot/heron_base/launch/cal.launch
    echo "Restart ROS service to begin using saved calibration."
  fi
fi
