#!/bin/bash
source `rospack find rosbash`/rosbash

# Install the upstart job and launch files.
rosrun robot_upstart install kingfisher_bringup/launch/core --job kingfisher-core

# Install the udev rules.
rospd kingfisher_bringup/udev > /dev/null
echo "Installing udev rules."
sudo cp *.rules /etc/udev/rules.d/
popd > /dev/null
sudo udevadm trigger

# Configure ublox GPS.
rospd kingfisher_bringup/config > /dev/null
if [ -e /dev/ublox ]; then
  echo "Attempting to configure ublox GPS."
  sed '/^\#/d' ublox.hex | xxd -r -p > /dev/ublox
else
  echo "Can't find ublox GPS to configure it. Please replug it and rerun this script."
fi
popd > /dev/null
