#!/bin/bash
source `rospack find rosbash`/rosbash

# Check for kingfisher_controller package.
rospack find kingfisher_controller > /dev/null
if [[ "$?" != "0" ]]; then
  echo "Cannot find kingfisher_controller package. Please contact Clearpath Robotics"
  echo "for instructions on installing the Kingfisher supplementary packages."
  exit 1 
fi

# Install the upstart job and launch files.
rosrun robot_upstart install kingfisher_bringup/launch/core --job kingfisher-core \
                               --interface ${1-${ROBOT_NETWORK-eth0}} \
                               --setup ${ROBOT_SETUP-$(roscd; echo `pwd`/setup.bash)}

# Install the default compass calibration.
COMPASS_YAML=/etc/ros/$ROS_DISTRO/imu_compass.yaml
if [ -e "$COMPASS_YAML" ]; then
  echo "Compass yaml config already exists, skipping."
else 
  echo "Installing compass yaml file to $COMPASS_YAML"
  sudo cp "$(rospack find kingfisher_bringup)/config/imu_compass.yaml" "$COMPASS_YAML"
fi

# Install the default controller configuration.
CONTROLLER_YAML=/etc/ros/$ROS_DISTRO/kingfisher_controller.yaml
if [ -e "$CONTROLLER_YAML" ]; then
  echo "Controller yaml config already exists, skipping."
else
  echo "Installing controller yaml file to $CONTROLLER_YAML"
  sudo cp "$(rospack find kingfisher_controller)/config/kingfisher_controller.yaml" "$CONTROLLER_YAML"
fi

# Install the udev rules.
rospd kingfisher_bringup/udev > /dev/null
echo "Installing udev rules."
sudo cp *.rules /etc/udev/rules.d/
popd > /dev/null
sudo udevadm trigger

# Configure ublox GPS.
rospd kingfisher_bringup/config > /dev/null
if [ -e /dev/ublox ]; then
  echo "Attempting to configure ublox GPS."
  sed '/^\#/d' ublox.hex | xxd -r -p > /dev/ublox
else
  echo "Can't find ublox GPS to configure it. Please replug it and rerun this script."
fi
popd > /dev/null
