#!/bin/bash

# Install the upstart job and launch files.
rosrun upstart install pkg=kingfisher_bringup job=core

# Install the udev rules.
rospd kingfisher_bringup/udev
sudo cp * /etc/udev/rules.d/
popd

# Configure ublox GPS.
rospd kingfisher_bringup/config
if [ -e /dev/ublox ]; then
  echo "Attempting to configure ublox GPS."
  sed '/^\#/d' ublox.hex | xxd -r -p > /dev/ublox
else
  echo "Can't find ublox GPS to configure it. Please replug it and rerun this script."
fi
popd
